#include "graphics.h"
#include "gba.h"
// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
#include "images/img_header.h"

#include <stdio.h>

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

static void updateDrag(Drag *drag){
    if(!drag->onFire && drag->direction == RIGHT){
        drawImageDMA(drag->col, drag->row, DRAG_RIGHT_WIDTH, DRAG_RIGHT_HEIGHT, drag_right);
    } else if(!drag->onFire && drag->direction == LEFT){
        drawImageDMA(drag->col, drag->row, DRAG_LEFT_WIDTH, DRAG_LEFT_HEIGHT, drag_left);
    } else if(drag->onFire && drag->direction == LEFT){
        drawImageDMA(drag->col, drag->row, DRAG_FIRE_LEFT_WIDTH, DRAG_FIRE_LEFT_HEIGHT, drag_fire_left);
    } else {
        drawImageDMA(drag->col, drag->row, DRAG_FIRE_RIGHT_WIDTH, DRAG_FIRE_RIGHT_HEIGHT, drag_fire_right);
    }
}

static void clearDrag(Drag *drag)
{
    if(drag->onFire){
        drawPartOfFullScreenImageDMA(drag->col, drag->row, DRAG_FIRE_RIGHT_WIDTH, DRAG_FIRE_RIGHT_HEIGHT, castle);
    } else{
        drawPartOfFullScreenImageDMA(drag->col, drag->row, DRAG_RIGHT_WIDTH, DRAG_RIGHT_HEIGHT, castle);
    }
}

static void updateSpiders(Spider * spiders){
    for (int i = 0; i < MAX_SPIDERS; i++){
        if(spiders[i].show){
            drawImageDMA(spiders[i].col, spiders[i].row, SPIDER_WIDTH, SPIDER_HEIGHT, spider);
        }
    }
}

static void clearSpiders(Spider * spiders){
    for (int i = 0; i < MAX_SPIDERS; i++){
        if(spiders[i].show){
            drawPartOfFullScreenImageDMA(spiders[i].col, spiders[i].row, SPIDER_WIDTH, SPIDER_HEIGHT, castle);
        }
    }
}

static void updateFireball(Fireball *f){
    if(f->show){
        drawImageDMA(f->col, f->row, FIREBALL_WIDTH, FIREBALL_HEIGHT, fireball);
    }
}

static void clearFireball(Fireball *f){
    drawPartOfFullScreenImageDMA(f->col, f->row, FIREBALL_WIDTH, FIREBALL_HEIGHT, castle);
}

static void updateText(int score, int charges){
    char buffer[10];
    sprintf(buffer, "SCORE %d", score);
    drawString(0, 5, buffer, RED);

    sprintf(buffer, "CHARGE %d", charges);
    drawString(GBA_WIDTH - 75, 5, buffer, RED);
}

static void clearText(void){
    drawRectDMA(0, 5, 50, 10, BLACK);
    drawRectDMA(GBA_WIDTH - 75, 5, 50, 10, BLACK);
}

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // fillScreenDMA(BACKGROUND_COLOR);
    drawFullScreenImageDMA(castle);
    updateDrag(&state->drag);
    updateSpiders(state->spiders);
    updateFireball(&state->fireball);
    updateText(state->score, state->charges);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    // UNUSED(state);
    clearDrag(&state->drag);
    clearSpiders(state->spiders);
    clearFireball(&state->fireball);
    clearText();
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    updateDrag(&state->drag);
    updateSpiders(state->spiders);
    updateFireball(&state->fireball);
    updateText(state->score, state->charges);
}
